# Use root/123456 as user/password credentials
version: "3.1"

services:
  mariadb:
    container_name: sillage-ui__mysql
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx: #项目的service name
    container_name: sillage-ui__nginx
    image: nginx #指定镜像
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      - ./web/website/dist:/usr/share/nginx/website/ #挂载项目
      - ./web/preview/dist:/usr/share/nginx/preview/ #挂载项目
    privileged: true
